version: "3.1"

services:
  db:
    image: "akoller/low-memory-mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: php@php.php
      MYSQL_DATABASE: curriculum
      MYSQL_USER: user
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./db/:/var/lib/mysql/
      - ./init.sql:/docker-entrypoint-initdb.d/schema.sql:ro
  web:
    image: nginx:latest
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./www-data:/www-data
      - ./nginxWebsite.conf:/etc/nginx/conf.d/default.conf
  php:
    build: .
    volumes:
      - ./www-data:/www-data
